# Generated by Django 4.2.7 on 2025-08-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="myapp/images/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
