# Generated by Django 4.2.7 on 2025-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("is_live", models.BooleanField(default=False)),
                ("playback_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
