# Generated by Django 4.2.7 on 2025-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailynews",
            old_name="html_summary",
            new_name="summary_html",
        ),
        migrations.AlterField(
            model_name="dailynews",
            name="date",
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
