# Generated by Django 4.2.7 on 2025-08-30 11:57

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("ads", "0005_ad_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="text",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="picture",
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ads_pictures/"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
