# Generated by Django 4.2.7 on 2025-07-31 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mystocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprice",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
