# Generated by Django 4.2.7 on 2024-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="image/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
