services:
  - type: web
    name: pleasurewebsite
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application --chdir mysite
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: PYTHON_VERSION
        value: 3.11
