# Generated by Django 4.2.7 on 2025-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_arranged",
            field=models.BooleanField(default=False),
        ),
    ]
