# Generated by Django 4.2.7 on 2025-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_material_is_arranged"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="remark",
            field=models.TextField(blank=True),
        ),
    ]
