# Generated by Django 4.2.7 on 2025-03-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatHistory",
        ),
    ]
