# Generated by Django 4.2.7 on 2025-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
