# Generated by Django 4.2.7 on 2025-08-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_pageview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageView",
        ),
    ]
