# Generated by Django 4.2.7 on 2024-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hname", models.CharField(max_length=100)),
                ("tariff", models.DecimalField(decimal_places=2, max_digits=5)),
                ("complementry", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15, unique=True)),
                ("address", models.TextField()),
                ("remark", models.TextField()),
            ],
        ),
    ]
