# Generated by Django 4.2.7 on 2025-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="invited",
            field=models.BooleanField(default=False),
        ),
    ]
