# Generated by Django 4.2.7 on 2025-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_contact_arrival_date_contact_arrival_ref_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
            ],
        ),
    ]
