# Generated by Django 4.2.7 on 2025-04-11 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_eventschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventschedule",
            name="start_time",
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="date",
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="time",
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="venue",
            field=models.CharField(default="Main Hall", max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="myapp.eventschedule",
                    ),
                ),
            ],
        ),
    ]
