# Generated by Django 4.2.7 on 2025-04-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_eventschedule_start_time_eventschedule_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="event",
        ),
        migrations.DeleteModel(
            name="EventSchedule",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
    ]
