# Generated by Django 4.2.7 on 2025-08-24 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        help_text="Type your daily greeting here. It will be used for all contacts."
                    ),
                ),
                (
                    "message_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload the image you created in GIMP.",
                        null=True,
                        upload_to="daily_images/",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="The date this message is for.",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
