# Generated by Django 4.2.7 on 2025-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
