# Generated by Django 4.0.7 on 2024-07-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('Address', models.TextField()),
                ('Remark', models.TextField()),
            ],
        ),
    ]
