# Generated by Django 4.2.7 on 2024-08-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_hotel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hotel",
        ),
    ]
